services:
  frontend:
    type: static
    name: math-frontend
    buildCommand: npm run build
    staticPublishPath: dist/public
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true

  # Optionally, you can add a backend or database service if needed
  # backend:
  #   type: web
  #   name: math-backend
  #   env: node
  #   plan: free
  #   buildCommand: npm install && npm run build
  #   startCommand: npm run start
  #   envVars:
  #     - key: NODE_ENV
  #       value: production
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: math-db
  #         property: connectionString
  #   autoDeploy: true
  #   healthCheckPath: /api/health
  #
  # database:
  #   type: postgres
  #   name: math-db
  #   plan: free
